### ISSUE TITLE
Erläuterung der Noten 

### ISSUE THREAD

**Issue by SickMi** [Fuenfgeld/DMA2022DataProjectA#33]
Hallo Herr @Fuenfgeld , könnten Sie uns die Zusammensetzung der Noten erklären? Bzw. die einzelne Benotung in den letzten beiden Abgaben mitteilen?

**Comment by Fuenfgeld** [comment]
Wer Feedback will zu euren Datenprojekten oder zu den Noten kann sich heute um 4:30 Uhr in den google classroom einwählen.

Viele Grüße,
